import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'cloud_storage_constants.dart';

///a class to represent the structure of documents
///every note / document generated by the cloud firebase must have a unique id
@immutable
class CloudNote {
  final String documentId;
  final String ownerUserId;
  final String noteContent;

  const CloudNote({
    required this.documentId,
    required this.ownerUserId,
    required this.noteContent,
  });

  ///we need the firestore cloud snapshot
  CloudNote.fromSnapshot(QueryDocumentSnapshot<Map<String, dynamic>> snapshot)
      : documentId = snapshot.id,
        ownerUserId = snapshot.data()[ownerUserIdFieldName],
        noteContent = snapshot.data()[textFieldName] as String;
}
